[phases.setup]
aptPkgs = ['nodejs']

[phases.install]
cmds = [
  'cd /app/client && npm install',
  'cd /app/server && npm install'
]

[phases.build]
cmds = [
  'cd /app/client && npm run build',
  'mkdir -p /app/server/client',
  'cp -r /app/client/build /app/server/client/'
]

[start]
cmd = 'cd /app/server && npm start'